# Generated by Django 4.0.5 on 2022-06-13 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(0)]),
        ),
    ]
